version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: e-consultancy-db
    environment:
      POSTGRES_DB: e_consultancy
      POSTGRES_USER: consultancy_user
      POSTGRES_PASSWORD: consultancy_2025
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: e-consultancy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@econsultancy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
